name: Dynamic Memory Check - Valgrind

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  Valgrind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: apt install dependency
        run: |
          sudo apt-get -y install valgrind
          sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
      - name: build
        run: make -C 3_Implementation/
      - name: make test
        run: make test -C 3_Implementation/
      - name: Valgrind
        run: make leak -C 3_Implementation/
